import { Todos } from './todos.model';

export const todoList: Todos[] = [
  {
    id: 1,
    todo: 'Komponente zur Verwaltung der Todos erstellen',
    category: 'Todos',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 2,
    todo: 'offene Aufgaben als hardcodierten Array erledgen',
    category: 'Todos',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 3,
    todo: 'Progressbar fuer offene Aufgaben',
    category: 'Todos',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 4,
    todo: 'Todos sortieren, filtern & Pagination',
    category: 'Todos',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 5,
    todo: 'Header, Menüs und Routing erstellen',
    category: 'Framework',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 6,
    todo: 'Sidenav erstellen',
    category: 'Framework',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 7,
    todo: 'Willkommens-Seite erstellen',
    category: 'Framework',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 8,
    todo: 'Login Formular erstellen',
    category: 'Login',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 9,
    todo: 'Login und Logout in firebase',
    category: 'Login',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 10,
    todo: 'Menüpunkte abhängig von Login anzeigen',
    category: 'Login',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 11,
    todo: 'Datenmodell in app und firebase erstellen',
    category: 'Kurse',
    type: 'neu',
    status: 'aktiv',
  },
  {
    id: 12,
    todo: 'Testdaten für Anzeige in firebase erfassen',
    category: 'Kurse',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 13,
    todo: 'Kurs-Übersicht als aufklappbares Akkordeon anzeigen',
    category: 'Kurse',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 14,
    todo: 'Detaildaten eines Kurses anzeigen',
    category: 'Kurse',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 15,
    todo: 'Formular zum Erfassen/Ändern der Kursdaten erstellen',
    category: 'Kurse',
    type: 'neu',
    status: 'aktiv',
  },
  {
    id: 16,
    todo: 'Kursdaten in firebase speichern',
    category: 'Kurse',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 17,
    todo: 'Kursbestätigungs-Image auswählen/anzeigen und speichern',
    category: 'Kurse',
    type: 'neu',
    status: 'aktiv',
  },
  {
    id: 18,
    todo: 'Datenerfassung: Kurse mittels App erfassen',
    category: 'Kurse',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 19,
    todo: 'Konzept für Kursdatenanzeige erstellen',
    category: 'Kurse',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 20,
    todo: 'Konzept für Kursverwaltung erstellen',
    category: 'Kurse verwalten',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 21,
    todo: 'Entitäten für Dropdowns definieren, div. Tech.Stack',
    category: 'Kurse verwalten',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 22,
    todo: 'Generisches Wartungs-Programm für Filter erstellen',
    category: 'Kurse verwalten',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 23,
    todo: 'div. Entitäten in Firebase erstellen',
    category: 'Kurse verwalten',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 24,
    todo: 'Einbinden der Stammdaten-Programme in Framework',
    category: 'Kurse verwalten',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 25,
    todo: 'Temp.Solution: hardcodierte Filterarrays - später Speichern in DB',
    category: 'Kurse verwalten',
    type: 'neu',
    status: 'aktiv',
  },
  {
    id: 26,
    todo: 'Kurs löschen',
    category: 'Kurse verwalten',
    type: 'neu',
    status: 'aktiv',
  },
  {
    id: 27,
    todo:
      'eigenen Testuser erstellen, damit auch Kursverwaltung freigeschaltet wird',
    category: 'Admin-Funktion freigeben',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 28,
    todo: 'eigene Collection für Kurse durch Testuser erstellen',
    category: 'Admin-Funktion freigeben',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 29,
    todo: 'Switchen zwischen Zoe-Kursen und user-defierten Kursen',
    category: 'Admin-Funktion freigeben',
    type: 'neu',
    status: 'offen',
  },
];
