import { Todos } from './todos.model';

export const todoList: Todos[] = [
  {
    id: 1,
    todo: 'Komponente zur Verwaltung der Todos erstellen',
    category: 'Todos',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 2,
    todo: 'offene Aufgaben als hardcodierten Array erledgen',
    category: 'Todos',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 3,
    todo: 'Progressbar fuer offene Aufgaben',
    category: 'Todos',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 4,
    todo: 'Todos sortieren, filtern & Pagination',
    category: 'Todos',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 5,
    todo: 'Header, Menüs und Routing erstellen',
    category: 'Framework',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 6,
    todo: 'Sidenav erstellen',
    category: 'Framework',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 7,
    todo: 'Willkommens-Seite erstellen',
    category: 'Framework',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 8,
    todo: 'Login Formular erstellen',
    category: 'Login',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 9,
    todo: 'Login und Logout in firebase',
    category: 'Login',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 10,
    todo: 'Menüpunkte abhängig von Login anzeigen',
    category: 'Login',
    type: 'neu',
    status: 'erledigt',
  },
  {
    id: 11,
    todo: 'Datenmodell in app und firebase erstellen',
    category: 'Kurse',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 12,
    todo: 'Testdaten für Anzeige in firebase erfassen',
    category: 'Kurse',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 13,
    todo: 'Kursdaten als Card mit Screenshot anzeigen',
    category: 'Kurse',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 14,
    todo: 'Detaildaten einer Card anzeigen',
    category: 'Kurse',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 15,
    todo: 'Formular zum Erfassen der Kursdaten erstellen',
    category: 'Kurse',
    type: 'neu',
    status: 'aktiv',
  },
  {
    id: 16,
    todo: 'Kursdaten in firebase speichern',
    category: 'Kurse',
    type: 'neu',
    status: 'aktiv',
  },
  {
    id: 17,
    todo: 'Screenshot als Bilder für Cards erstellen',
    category: 'Kurse',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 18,
    todo: 'Beschreibungen der Kurse erstellen',
    category: 'Kurse',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 19,
    todo: 'Konzept für Kursdatenanzeige erstellen',
    category: 'Kurse',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 20,
    todo: 'Konzept für Kursverwaltung erstellen',
    category: 'Kurse erfassen',
    type: 'neu',
    status: 'aktiv',
  },
  {
    id: 21,
    todo: 'Entitäten für Dropdowns definieren, div. Tech.Stack',
    category: 'Kurse erfassen',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 22,
    todo: 'div. Stammdatenprogramme erstellen',
    category: 'Kurse erfassen',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 23,
    todo: 'div. Entitäten in Firebase erstellen',
    category: 'Kurse erfassen',
    type: 'neu',
    status: 'offen',
  },
  {
    id: 24,
    todo: 'Einbinden der Stammdatenprogramme in Framework',
    category: 'Kurse erfassen',
    type: 'neu',
    status: 'aktiv',
  },
];
